mod 'homebrew',    '2.1.0', :github_tarball => 'boxen/puppet-homebrew'
mod 'module-data', '0.0.1',  :github_tarball => 'ripienaar/puppet-module-data'
mod 'stdlib',      '4.7.0',  :github_tarball => 'puppetlabs/puppetlabs-stdlib'
mod 'sudo',        '1.0.0',  :github_tarball => 'boxen/puppet-sudo'
