mod 'homebrew', '0.0.16', :github_tarball => 'boxen/puppet-homebrew'
mod 'sudo',     '0.0.1',  :github_tarball => 'boxen/puppet-sudo'
mod 'stdlib',   '3.0.0',  :github_tarball => 'puppetlabs/puppetlabs-stdlib'
