#!/bin/sh

[ ! -f bin/rspec ] && {
  script/bootstrap
}

echo
echo "Spec"
echo "----"

specs=`find spec -name '*_spec.rb' -not -path 'spec/fixtures/*' -print | tr "\n" ' '`

# Run the specs sequentially due to autoloader issue
for spec in $specs; do
  bin/rspec $spec 2>/dev/null
  if [ $? -ne 0 ]; then
    exit 1
  fi
done
